### ISSUE TITLE
Support build-std feature

### ISSUE THREAD

**Issue by fzzr-** [rtsuk/crank#7]
That's neat [nightly feature][build-std] with which we don't need [cargo-xbuild][].
Just add args `cargo +nightly -Z build-std --target=thumbv7em-none-eabihf` to cargo call for native build (I mean `--device`).

I have already tested it for [hello_world example][] and it works perfectly!

[cargo-xbuild]: https://crates.io/crates/cargo-xbuild
[build-std]: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#build-std
[hello_world example]: https://github.com/rtsuk/crankstart/blob/main/examples/hello_world.rs

**Comment by rtsuk** [comment]
I will have to check it out. Feel free to hack up a crank patch if you like.
